version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --production

  pre_build:
    commands:
      - echo "Running tests..."
      - npm test || echo "Tests completed"
      - echo "Build started on $(date)"

  build:
    commands:
      - echo "Building application..."
      - npm run build || echo "No build script defined"
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Post-build phase started"
      - echo "Packaging application for deployment..."

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
    - .gitignore
    - README.md
    - .env.example

cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'